[tools]
go = "latest"
node = "lts"
python = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python", "node"]
legacy_version_file = true
