# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Fix colors
set -g default-terminal "tmux-256color"
set -a terminal-features "$TERM:RGB"
set -g focus-events on

set -sg escape-time 0

# style — Catppuccin Macchiato
set -g status-bg "#24273a"
set -g status-fg "#cad3f5"
set -g status-left "#[fg=#8aadf4]  "
set -g status-right "[#[fg=#8aadf4]#S#[fg=#cad3f5]]"
set -g status-position top
set -g status-justify centre
set -g window-status-current-format "#[underscore]#I:#W"
set -g window-status-format "#I:#W"

# use system clipboard
set -g set-clipboard on

# vim bindings
set -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# allow resizing panes with the mouse
set -g mouse on

# start window index on 1 and renumber windows when closing
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# open new windows in the cwd
bind c new-window -c "#{pane_current_path}"

# open splits in cwd
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# open lazygit in a temp window
bind g new-window -c "#{pane_current_path}" "lazygit"
# open lazydocker in a temp window
bind D new-window -c "#{pane_current_path}" "lazydocker"
