$font = CaskaydiaMono Nerd Font

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 0, 0, 1, 1
    animation = fadeIn,          1, 5, linear
    animation = fadeOut,         1, 5, linear
    animation = inputFieldDots,  1, 2, linear
}

background {
    monitor =
    path = screenshot                        # blurred screenshot at lock time
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0)
    outer_color = rgba(7aa2f7ee) rgba(bb9af7ee) 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color  = rgba(ff6633ee) rgba(ff0066ee) 40deg
    font_color  = rgb(8f8f8f)
    fade_on_empty = false
    rounding = 15
    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL
    dots_spacing = 0.3
    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font
    position = -30, 0        # default: top-right
    # position = 0, 120      # alternative: centered
    halign = right
    valign = top
    # halign = center        # uncomment with centered position
    # valign = center        # uncomment with centered position
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 25
    font_family = $font
    position = -30, -150     # default: top-right
    # position = 0, 40       # alternative: centered
    halign = right
    valign = top
    # halign = center        # uncomment with centered position
    # valign = center        # uncomment with centered position
}
