# =============================================================================
# hyprpaper.conf
# =============================================================================

preload = ~/.local/share/wallpaper.jpg

# Apply to all monitors
wallpaper = ,contain:~/.local/share/wallpaper.jpg

# Silence the splash screen
splash = false
